server:
  port: 8083
spring:
  application:
    name: Blog_authms
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: "root"
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
